### ISSUE TITLE
ModuleNotFoundError: No module named 'nets.nets_zoo'

### ISSUE THREAD

**Issue by gden138** [williamzhao95/Pay-More-Attention#2]
Thank you very much for your release, I installed the environment as required, but the error message at runtime is as follows:
File "train_net.py", line 14, in <module>
    from nets.nets_zoo import get_model
ModuleNotFoundError: No module named 'nets.nets_zoo'
I want to know how to solve it.Thank you very much.

**Comment by williamzhao95** [comment]
This is a package import problem, you can try to modify the relative path of the import

**Comment by gden138** [comment]
Which path is this package? I don't find it. I'm not familiar with MXNet.
Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "williamzhao95/Pay-More-Attention"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 上午10:14
收件人:&nbsp;"williamzhao95/Pay-More-Attention"<Pay-More-Attention@noreply.github.com&gt;;
抄送:&nbsp;"yifan"<120828069@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [williamzhao95/Pay-More-Attention] ModuleNotFoundError: No module named 'nets.nets_zoo' (#2)





 
This is a package import problem, you can try to modify the relative path of the import

**Comment by williamzhao95** [comment]
This .py is replaced by resnetv1 and can be brought in from resnet_v1

**Comment by gden138** [comment]
I modify：
from nets.resnet_v1 import  ResNetV1
from gluoncv.model_zoo import get_model

#base_net = get_model(name=config.BASE_MODEL_NAME, num_classes=config.NUM_CLASSES)
    base_net =  ResNetV1(name=config.BASE_MODEL_NAME, num_classes=config.NUM_CLASSES)
but：
File "train_net.py", line 312, in <module>
    train_base_net(train_dataloader, test_dataloader, logger)
  File "train_net.py", line 245, in train_base_net
    base_net =  ResNetV1(name=config.BASE_MODEL_NAME, num_classes=config.NUM_CLASSES)
TypeError: __init__() missing 3 required positional arguments: 'block', 'layers', and 'channels'

**Comment by gden138** [comment]
Can I add your QQ? my qq 120828069，I need to quote your paper and make a comparison
Thank you very much.

**Comment by williamzhao95** [comment]
This may be a bug, I will fix it later
