### ISSUE TITLE
Ref to add

### ISSUE THREAD

**Issue by robmarkcole** [williamzhao95/Pay-More-Attention#4]
https://ieeexplore.ieee.org/abstract/document/9157951

**Comment by williamzhao95** [comment]
Thanks. Z. Zhao, J. Li, Z. Luo, J. Li and C. Chen, "Remote Sensing Image Scene Classification Based on an Enhanced Attention Module," in IEEE Geoscience and Remote Sensing Letters, vol. 18, no. 11, pp. 1926-1930, Nov. 2021, doi: 10.1109/LGRS.2020.3011405.
