### ISSUE TITLE
conv3x3

### ISSUE THREAD

**Issue by shenhaibb** [williamzhao95/Pay-More-Attention#5]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/64736467/173085409-761fa4d0-9cfe-4b61-816f-6dc2d112e93d.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/64736467/173085598-87aa0768-607e-4144-b25a-0b9d611e3374.png">
In the source code, i only see a 3x3 convolution, why is the paper is two

**Comment by williamzhao95** [comment]
It's actually supposed to be two 3x3 convolutions, the open source version of the code is older.

**Comment by williamzhao95** [comment]
It's actually supposed to be two 3x3 convolutions, the open source version of the code is older.
